### ISSUE TITLE
AndEvery() is not relative to the specified start time?

### ISSUE THREAD

**Issue by Oculys-DanL** [fluentscheduler/FluentScheduler#124]
Hi there, great library!

Considering the following:

```
jobRegistry.Schedule(new DownloadJob(downloadTask.ReportId)).
WithName(downloadTask.ReportId)
.ToRunOnceAt(1,0)
.AndEvery(15).Minutes();
```
If I schedule a job as above, it will always run immediately and then every 15 minutes afterwards without any regard to the 1:00 start time. I was wondering if there was a way to schedule a job that respects the start time so that it would always run, for example at: *:00, *;15, *:30, *:45, no matter what time the JobManager starts?

I may work on adding such a feature if I have not missed something and it already exists.

Thanks,

**Comment by tallesl** [comment]
Sorry for taking so long to answer!

If you specify a time that is greater than the current time (passing 15h while it's 11h for example) the library takes it as a late schedule and runs it right away.

Looks like `AndEvery` is innocent, the culprit is `ToRunOnceAt`: [the library uses the year, month and day of today](https://github.com/fluentscheduler/FluentScheduler/blob/5.1.4/Library/Schedule.cs#L141) on `ToRunOnceAt`.

That's a bug alright, it's just too counterintuitive to realize that (I had to look on the source code myself). It's incredible that it's been like that from the [very beginning of the library back on 2012](https://github.com/fluentscheduler/FluentScheduler/blob/e8361dd/FluentScheduler/Model/Schedule.cs#L63).

The fix is easy: I'm assuming [tomorrow](https://github.com/fluentscheduler/FluentScheduler/blob/df84c00/Library/Schedule.cs#L158) for the date if the time is greater than the time right now. I let you know here when the package is published.

**Comment by mdissel** [comment]
> If you specify a time that is greater than the current time (passing 15h while it's 11h for example) the library takes it as a late schedule and runs it right away.

Why should it run immediately when you specify a later time? If you want it to run now, use the ToRunNow()

**Comment by tallesl** [comment]
> Why should it run immediately when you specify a later time? If you want it to run now, use the ToRunNow()

It's the other way around ("passing 11h while it's 15h"). Edited.

**Comment by mdissel** [comment]
Hmm. I'm not sure if the scheduler should start missed scheduled items.. Does it mean that it runs all missed schedules for the current day? Maybe make this an optional feature?

**Comment by tallesl** [comment]
I can't really picture a scenario which you should run the schedule right now if the hour and minute specified is earlier than now. I picture that the typical usage of `ToRunOnceAt` it's things like running a task when the server load is low or avoiding notifying an user in a inconvenient hour.

(note that the change in question applies only to `ToRunOnceAt`, the rest of the library stay as it is)

**Comment by tallesl** [comment]
Just published on [nuget.org](http://nuget.org), version 5.2.0.
