### ISSUE TITLE
Dependency Injection, Simple Injector

### ISSUE THREAD

**Issue by nvsoares** [fluentscheduler/FluentScheduler#126]
Hi.
I'm using Simple Injector for DI. In the documentation you have an example of how to use Dependency Injection with StructureMap. How to use with Simple Injector?

**Comment by jplindgren** [comment]
You have to create a IJobFactory in the same  way as you do with StructureMap, but using SimpleInjector container.
For instance:
```
var simpleInjectorContainer = new Container();
simpleInjectorContainer.Register<IDependency, MyDependency>();
simpleInjectorContainer.Register<MyJob>();
JobManager.JobFactory = new SimpleInjectorJobFactory(simpleInjectorContainer);

public class SimpleInjectorJobFactory : IJobFactory
{
    readonly Container container;
    public SimpleInjectorJobFactory(Container simpleInjectorContainer){
         this.container = simpleInjectorContainer;
   }
    public IJob GetJobInstance<T>() where T : IJob
    {
        return container.GetInstance<T>();
    }
}
```

**Comment by tallesl** [comment]
The implementation will be almost the same for any DI library out there (Unity, Castle Windsor, ...).

Thanks for the snippet, @jplindgren!

**Comment by nvsoares** [comment]
I followed the example in the topic 'Using it with ASP.NET' and the snippet of @jplindgren and whenever the job is executed I get error in the GetJobInstance method:

> 
An exception of type 'SimpleInjector.ActivationException' occurred in SimpleInjector.dll but was not handled in user.
Additional information: The MyJob is registered as 'Web API Request' lifestyle, but the instance is requested outside the context of a Web API Request.
> 

Here's my code:

- Global.asax
```
    public class WebApiApplication : HttpApplication
    {
        protected void Application_Start()
        {
            GlobalConfiguration.Configure(WebApiConfig.Register);
            GlobalConfiguration.Configure(DependencyInjection.Register);
        }
    }
```

- WebApiConfig
```
public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services
           
            config.MessageHandlers.Add(new AddCorrelationIdToResponseHandler());

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }
```

- DependencyInjection
```
public class DependencyInjection
    {
        public static void Register(HttpConfiguration config)
        {
            // Create the container as usual.
            var container = new Container();
            container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();

            // Register your types, for instance using the scoped lifestyle:
            container.Register<Interfaces.IProducts, Implementations.Products>(Lifestyle.Scoped);
            container.Register<Interfaces.ILogger, Implementations.Logger>(Lifestyle.Scoped);

            container.Register<Implementations.Jobs.MyJob>(Lifestyle.Scoped);
            JobManager.JobFactory = new SimpleInjectorJobFactory(container);
            JobManager.Initialize(new Implementations.Scheduler.Registry());

            container.RegisterWebApiControllers(GlobalConfiguration.Configuration);

            GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);
        }

    }
```

- SimpleInjectorJobFactory
```
public class SimpleInjectorJobFactory : IJobFactory
    {
        readonly Container Container;
        public SimpleInjectorJobFactory(Container container)
        {
            this.Container = container;
        }
        public IJob GetJobInstance<T>() where T : IJob
        {
            return Container.GetInstance<MyJob>();
        }
    }
```

- Registry 
```
    public class Registry : FluentScheduler.Registry
    {
        public Registry()
        {
            // Schedule an IJob to run at an interval
            Schedule<MyJob>().NonReentrant().ToRunEvery(1).Minutes();
        }
    }
```

- MyJob 
```
public class MyJob : FluentScheduler.IJob, IRegisteredObject
    {
        private readonly object _lock = new object();
        private bool _shuttingDown;

        public MyJob()
        {
            //Register this job with the hosting environment.
            //Allows for a more graceful stop of the job, in the case of IIS shutting down.
            HostingEnvironment.RegisterObject(this);
        }

        void IJob.Execute()
        {
            lock (_lock)
            {
                if (_shuttingDown) return;

                // Do work, son!
            }

        }

        void IRegisteredObject.Stop(bool immediate)
        {
            // Locking here will wait for the lock in Execute to be released until this code can continue.
            lock (_lock)
            {
                _shuttingDown = true;
            }

            HostingEnvironment.UnregisterObject(this);
        }
    }
```


What am I doing wrong?

**Comment by jplindgren** [comment]
Well, my english is not that good but i´ll try to help you.
Looking at your code seems that the problem is not about FluentScheduler+SimpleInjector, but the understanding about how the containers in general treat the dependency lifetime manager.
I confess to you that I do not know much about SimpleFactory specifically, but the concept is the same for every container out there, so you just have to find how to do it with simple factory.
As you said, your job is registered with a scoped lifetime 'Web API Request'. This means that a instance of a dependency is created by the container per request and it is disposed when the request ends. 
Your job is running inside FluentScheduler and is not linked with the request. It acts like a background worker and will always run. That is why when your SimpleInjectorJobFactory tries to resolve the dependency, it throws exception because of the default scoped behavior set at 
`container.Options.DefaultScopedLifestyle = new WebApiRequestLifestyle();` 
tries to resolve the dependency per request.
In others containers, you solve that kind of problem with ChildContainers, for each diferent scope. In SimpleFactory seems that you have to create another scope Lifestyle when resolving the Jobs dependencies:
Try to change for instance your GetJobInstance inside SimpleInjectorJobFactory to:
```
public IJob GetJobInstance<T>() where T : IJob {
        using (Container.BeginExecutionContextScope()) {                
               return Container.GetInstance<MyJob>();
         }            
}
```
Try to learn more about the lifetimes in SimpleFactory [here](http://simpleinjector.readthedocs.io/en/latest/lifetimes.html.)
Take my solution with a grain of salt, because as i said before, i do not looked exaclty how SimpleFactory solves that problem.
In Unity for example, you can create ChildContainers, and set diferent lifetimes between them. I can have my ILogger as transient inside a Per Request Scope, but a singleton inside a Tenant Scope for example.

**Comment by nvsoares** [comment]
Hello @jplindgren 
Sorry for my response being so late. Your help was very helpful and it worked.
Thank you very much.

**Comment by nrjohnstone-coolblue** [comment]
public IJob GetJobInstance<T>() where T : IJob {
        using (Container.BeginExecutionContextScope()) {                
               return Container.GetInstance<MyJob>();
         }            
}

I'm pretty sure that does not work as you think it does.

As soon as you return the instance you are also ending the scope and you will end up with a disposed instance. It's pretty easy to test just make MyJob implement IDisposable and you will see it get called before the job even starts to be executed.

I think the current IJob interface doesn't support per request lifecycles in it's current format.
