### ISSUE TITLE
JobManager HttpContext.Current

### ISSUE THREAD

**Issue by nvsoares** [fluentscheduler/FluentScheduler#153]
Hello.
I have an ASP.NET api running on IIS. In the api pipeline I put a handler to generate a CorreletionId for each request that is added in a header of the same, in order to be able to log any request.
I also use the FluentScheduler to manage a queue. The task is triggered but then I get errors because the HttpContext.Current is always null.
Is it possible for FluentScheduler to instantiate the HttpContext.Current?

**Comment by tallesl** [comment]
HttpContext is null because FluentScheduler runs its jobs in a task of its own, in which the current http request context is not available.

[(this is a very common question)](http://google.com/search?q=httpcontext+current+null)

You can enclose the HttpContext in the job action (closure), but I wouldn't recommend it myself (what about the HttpContext lifetime)?

My suggestion is to redesign your job(s) in a way that doesn't use HttpContext.
