### ISSUE TITLE
Scheudler between two dates

### ISSUE THREAD

**Issue by alejandromartinez-8** [fluentscheduler/FluentScheduler#177]
hello!!, i would ask if i can do some similar to this.

Schedule(() => new TareaAEjecutar(tarea.webServiceTarea, item, urlLogin)).ToRunOnceAt(DateTime.Now.AddDays(diasFaltanEjecucion.Value)).AndEvery(tarea.conFrecuenciaSemanalYSeRepiteCadaNSemanas.Value).Weeks().On(DayOfWeek.Saturday).between(DateTime.now,DateTime.now.AddMonth(2));

I have date of start execution and date of finish and i need to do some similiar to this, any suggest??. It is an example. Other opcion is a method end(DateTime), which set the date of the end of execution.
thanks.

**Comment by VitorCioletti** [comment]
I'm afraid you the current version of the library does not support such thing. What you can do is put the Job to run at a certain date and manually stopping it when reaches a determined date.

What I believe the library is able to do in order to solve your problem is in the following code:

```c#
var registry = new Registry();
registry.Schedule(() => Console.WriteLine("Potato")).ToRunOnceAt(date).AndEvery(frequency).Weeks().On(DayOfWeek.Saturday).At(hours, minutes);
JobManager.Initialize(registry);
```

I hope it helps  :)

**Comment by tallesl** [comment]
Damn, I couldn't grasp a thing while reading the question.
I hope @VitorCioletti sorted things out.
