### ISSUE TITLE
How to use services inside jobs?

### ISSUE THREAD

**Issue by laccf** [fluentscheduler/FluentScheduler#180]
Hello, guys. I'm new using .Net and much more using FluentScheduler...
I'm trying to use a service that is already Scoped in the application in my job. I'm trying to use a simple get from a Service but I get null pointer.

Here is some part of the code:
**ResolverJob.cs**

```
    public class ResolverJob : IJob
    {
        private readonly IbService _bService;

//If this constructor stay here this job is never called. If the constructor is not here, I get null pointer.
        public ResolverJob(IbService bService)
        {
            _bService = bService;
        }

        public void Execute()
        {
            var bs = _bService.Get(); //here is where I get null pointer if I dont use the constructor. If I use the constructor the job is never called.
            long nextTickToExecute = long.MaxValue;
            long tickDateNow = DateTime.Now.Ticks;

            #region Next time to execute Scope

            #region Reschedule job Scope
            JobManager.Stop();
            var timeToExec = Convert.ToInt32(TimeSpan.FromTicks(nextTickToExecute).TotalSeconds);
            JobManager.Initialize(new SchedulerResolver("", timeToExec));
            #endregion
        }
    }
```

**SchedulerResolver.cs**
```
    public class SchedulerResolver : Registry
    {
        public SchedulerResolver(string msg, int secondsToExecute)
        {
            Console.WriteLine("[DEBUG] building scheduler.");
            Console.WriteLine("[DEBUG] msg [" + msg + "]");

            
            Schedule<ResolverJob>().WithName("SchedulerResolver").NonReentrant().ToRunOnceIn(secondsToExecute).Seconds();

        }
    }
```
**ConfigureServices inside Startup.cs**
```
public void ConfigureServices(IServiceCollection services)
{
	#region Services //all services are here
        services.AddScoped<IbService,bService>();
	#region Repository //all repositories are here
        services.AddScoped<IbRespository,bRespository>();

	JobManager.Initialize(new SchedulerResolver("",0)); // <-- here is where I initiate the job	
}
```

The scheduler is already working, but I need to use the **IbService** inside it. That is what i'm in trouble.

**Comment by tema5190** [comment]
Yeap, i have some question. How i can user built-in DI in ASP.Net Core 2.0+ ? I want to use my services and resolve them dependencies.

**Comment by laccf** [comment]
we solved using structure map, we couldn't find a way to use built-in

**Comment by tallesl** [comment]
An `IJob` implementation must have a parameterless constructor, as IntelliSense tells you:

![image](https://user-images.githubusercontent.com/3655047/34645870-daff35c4-f33f-11e7-830b-2f26d81d2aab.png)

You can hook up a `IJobFactory` on the library and change how the `IJob` instantiation is made (removing such restriction for instance), but using it is currently discouraged ([see README](https://github.com/fluentscheduler/FluentScheduler#dependency-injection)).

**Comment by zolakt** [comment]
This is really not a reason to close this ticket.
I'm having the same issue.
Nearly every .NET Core uses the built-in DI.
We shouldn't resort to 3rd party libs or hack to get this working.
This is essential functionality. 

Since you discourage the workaround, what is your solution for .NET Core apps?
Jobs without the ability to inject other code are useless.
Are you expecting us to drop DI completely just to use this lib?

**Comment by mitko993** [comment]
@zolakt 
I am new to this whole thing, and i agree with your statement. Listed through all possible threads still can't find a solution.

**Comment by tevert** [comment]
The recommended solution is to use any other DI framework. This library is removing support since it's somewhat messy to have a library responsible for more than one thing. 

```C#
Schedule(myDIContainer.Resolve<MyJob>())
                .ToRunEvery(1).Days().At(13, 55);
```

**Comment by welkie** [comment]
I think I've come up with a way to get this to work with ASP.NET's built in DI. It's a bit flawed though in that you still have to manually resolve your dependencies. My example uses an `ApplicationDbContext` dependency.

At the end of the `Startup` class's `Configure` method, I call `JobManager.Initialize` with an instance of my registry as usual, except my registry instance has an `IServiceProvider` instance passed in as an argument. It's the main service provider for the whole application. I get it by accessing `app.ApplicationServices`:

```csharp
// At the end of Startup.Configure

// Start jobs
JobManager.Initialize(new ApplicationRegistry(app.ApplicationServices));
```

My registry class uses that service provider instance by passing it in as arguments to manually constructed jobs:

```csharp
public class ApplicationRegistry : Registry
{
    public ApplicationRegistry(IServiceProvider sp)
    {
        Schedule(new AddDogJob(sp)).ToRunNow().AndEvery(3).Seconds();
        Schedule(new CountDogsJob(sp)).ToRunNow().AndEvery(5).Seconds();
    }
}
```

The jobs themselves use the service provider to create new scopes (can't access a scoped service like `ApplicationDbContext` otherwise), and use those new scopes' service providers to get instances of `ApplicationDbContext` to do the work:

```csharp
public class AddDogJob : IJob
{
    private readonly IServiceProvider _sp;

    public AddDogJob(IServiceProvider sp)
    {
        _sp = sp;
    }

    public void Execute()
    {
        using (var scope = _sp.CreateScope())
        {
            var db = scope.ServiceProvider.GetService(typeof(ApplicationDbContext)) as ApplicationDbContext;

            var jobId = Guid.NewGuid();
            var dogName = $"Fido({jobId})";

            var newDog = new Dog
            {
                Name = $"Fido({jobId})"
            };

            db.Dogs.Add(newDog);
            db.SaveChanges();

            Console.WriteLine($"Added new dog with name \"{dogName}\".");
        }
    }
}
```

I can see this becoming inconvenient if I have more services than just `ApplicationDbContext`. I welcome any advice for tying this in more naturally to ASP.NET Core's built in DI, where I wouldn't have to manually resolve instances of the services.

**Comment by yhnavein** [comment]
@welkie Your post should be a part of the documentation!
