### ISSUE TITLE
Job priority

### ISSUE THREAD

**Issue by adamThornton** [fluentscheduler/FluentScheduler#202]
Is it possible set priority on jobs.  I have a keep alive job that is not getting serviced at its rate when I kick off a one shot flood of 254 jobs (ping sweep).  I assume that I'm exceeding the theadpool size which is fine but I'd like to be able to set priority levels so the keep alive job gets serviced before any of the other jobs.

**Comment by tallesl** [comment]
I'm not so sure if [messing with thread priority while using a thread pool](https://stackoverflow.com/q/5589376) is a good idea... but you can try [this](https://stackoverflow.com/a/8791620).

By the way, is your thread pool really that loaded? Maybe there's something wrong with your tasks? Did you try changing the thread pool size?

I'm closing the issue but feel free to discuss it further (posting any progress on your issue is appreciated!).
