### ISSUE TITLE
Make CalculateNextRun public

### ISSUE THREAD

**Issue by mariuszjamro** [fluentscheduler/FluentScheduler#236]
Schedule's `CalculateNextRun` property is currently internal. Making it public would allow custom next run schedulers and easy integration with external libraries like [NCrontab](https://github.com/atifaziz/NCrontab).
    
    var crontabSchedule = CrontabSchedule.Parse(cronExpression);
    JobManager.AddJob(job, s => s.ToRunUsingScheduleProvider(crontabSchedule.GetNextOccurrence));

A method would be required accepting a CalculateNextRun-like function:

    public Schedule ToRunUsingScheduleProvider(Func<DateTime, DateTime> provider)

If you approve this i can provide a PR.

**Comment by VitorCioletti** [comment]
Hi @mariuszjamro,

The [newest version](#214) have already implemented Cron support through NCrontab API. I do not think it is a good ideia to publicly expose an internal component of the API because schedule calculations is all what FluentScheduler does, it has to . Also, it creates many possibilities to people screw things up and open issues on Github asking why this library does not work like it is supposed to. The older version suffers from a dependency injection issue due to the fact people just don't get it.
See (#228, #126, #160, #139)

I prefer to keep things simpler to avoid such issues.

If you want to help the development, we need someone to perform tests on the older version of the library to compare to the newest one because we completelly changed its architecture so it may have some bugs.

Closing this issue, if you think this matter is not dead yet, feel free to reopen it.

Thanks

:)
