### ISSUE TITLE
Can't use a for loop to schedule multiple jobs

### ISSUE THREAD

**Issue by Enoinoo** [fluentscheduler/FluentScheduler#245]
When I use a for loop to schedule `IJob`s, it seems like the jobs are not scheduled until loop ends. This messes up the parameters being passed in, if the index is being used as part of the parameters. It also threw an index out of boundary error, since I was using an array length as the for loop condition.

**Comment by VitorCioletti** [comment]
Could you please provide your source code?

**Comment by Enoinoo** [comment]
Of course

```cs
    class SimpleRegistry : Registry
    {
        public int[] secondIntervals;
        public SimpleRegistry(int[] secondIntervals)
        {
            this.secondIntervals = secondIntervals;
            ScheduleJobs();
            //these work fine
            //Schedule(() => new SimpleJob(0, 1)).ToRunNow().AndEvery(1).Seconds();
            //Schedule(() => new SimpleJob(1, 3)).ToRunNow().AndEvery(3).Seconds();
            //Schedule(() => new SimpleJob(2, 10)).ToRunNow().AndEvery(10).Seconds();
        }
        private void ScheduleJobs()
        {
            for (int i = 0; i < secondIntervals.Length; i++)
            {
                //this is where the problem is happening
                Schedule(() => new SimpleJob(i, secondIntervals[i])).ToRunNow().AndEvery(secondIntervals[i]).Seconds();
            }
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            JobManager.Initialize(new SimpleRegistry(new int[] { 1, 3, 10 }));
            Console.WriteLine("JobManager initialized, jobs should be running now. Press any key to exit...");
            Console.ReadKey();
        }
    }
```

**Comment by VitorCioletti** [comment]
>  it seems like the jobs are not scheduled until loop ends

It has nothing to do with your loop. Jobs are started after `JobManager.Initialize`is executed.

> It also threw an index out of boundary error, since I was using an array length as the for loop condition.

This is part of functional programming concepts in C# language called [Closures](https://csharpindepth.com/articles/Closures) and [Lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions).

```cs
Schedule(() => new SimpleJob(i, secondIntervals[i])).ToRunNow().AndEvery(secondIntervals[i]).Seconds();
```

When you use `() => new SimpleJob(i, secondIntervals[i])`, you are **creating a function** that instantiates a new `SimpleJob` and passing as parameter to another function ([see high order functions](http://functionalprogrammingcsharp.com/higher-order-functions)), so calling `secondsIntervals[i]`will not work as you want to. The exception is being thrown because the state of `i`variable is `3` after the loop ends. It works like this due to the fact a lambda expression stores its object references in memory, so thats why calling `() => new SimpleJob(i, secondIntervals[i])` works even though out of the`for` loop.

To solve this problem, just evaluate the index out of the lambda expression:

```cs
for (int i = 0; i < secondIntervals.Length; i++)
{
    var interval = secondIntervals[i];
    var newSimpleJob = new SimpleJob(i, interval);

     Schedule(() => newSimpleJob)).ToRunNow().AndEvery(secondIntervals[i]).Seconds();
}
```

Closing this issue, feel free to reopen it.

:)
