### ISSUE TITLE
[5.5.0] IAsyncJob proposal

### ISSUE THREAD

**Issue by jan-maria** [fluentscheduler/FluentScheduler#280]
Hello,

I've noticed a new IAsyncJob interface:

[https://github.com/fluentscheduler/FluentScheduler/blob/version-5/FluentScheduler/IAsyncJob.cs#L21](https://github.com/fluentscheduler/FluentScheduler/blob/version-5/FluentScheduler/IAsyncJob.cs#L21)

Wouldn't be it better to use GetAwaiter().GetResult() instead of simply Wait()?

``
Task.Run(ExecuteAsync).GetAwaiter().GetResult();
``

See [https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html#getawaitergetresult](https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html#getawaitergetresult)

Thank you,
Best regards,

**Comment by tallesl** [comment]
We're putting version 5 to sleep and focusing on releasing version 6, in which we started from scratch. I've only implemented `IAsyncJob` on version 5 because I could do it without messing with the inner workings of the library (see [#117](https://github.com/fluentscheduler/FluentScheduler/issues/117#issuecomment-667779897)).

I see your point, but I'm not changing it, especially because this problem also lies on [`JobManager`](https://github.com/fluentscheduler/FluentScheduler/blob/5.5.0/FluentScheduler/JobManager.cs#L461) and [you won't be dealing with `AggregateException` anyway](https://github.com/fluentscheduler/FluentScheduler/blob/5.5.0/FluentScheduler/JobManager.cs#L467-L470).
