### ISSUE TITLE
V5.5.0 wont upgrade with .Net 4.7.2 (from V5.4.0)

### ISSUE THREAD

**Issue by robvon** [fluentscheduler/FluentScheduler#281]
Quote:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'FluentScheduler 5.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by splendid25** [comment]
Hello,

Same problem here, the target is netstandard 2.1 since the support for IAsyncJob :
https://github.com/fluentscheduler/FluentScheduler/commit/17bd27827bcf1349ef11776e21a0c156d5a58ba7#diff-14344dff0cf6da478de76e11ced7ff7f

netstandard 2.1 does not support Full .NET Framework though...
https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md

**Comment by splendid25** [comment]
Could you target 2 Frameworks in the nuget package ?

Something like 

`<TargetFramework>netstandard2.0;netstandard2.1</TargetFramework>`

And 

```
#if NETSTANDARD2_1
        /// <summary>
        /// Executes the job, synchronously.
        /// </summary>
        void IJob.Execute()
        {
            ExecuteAsync().Wait();
        }
#endif
```

**Comment by huobazi** [comment]
Unfortunately, .NET Standard 2.1 can not support 4.6.1 upper...
https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by robvon** [comment]
Well I guess that's thanks for the breaking change. Pity; this was a really good product.

There is the comment in the 2.1 docs:

'Library authors who need to support .NET Framework customers should stay on .NET Standard 2.0.'

**Comment by igitur** [comment]
Semantic versioning would've been nice, i.e. breaking changes should go hand-in-hand with a major version increase.

**Comment by kvpt** [comment]
Like mentioned in https://github.com/fluentscheduler/FluentScheduler/issues/281#issuecomment-671808250.
I think the better solution here is to cross compile and target both .NET Standard 2.0 and .NET Standard 2.1.
With this feature only available for consumer under .NET Standard 2.1 because it's a big breaking change to change the runtime targeted.

**Comment by tallesl** [comment]
@splendid25

That seems a great solution, will try it out.

@robvon

You have all the right to report that the update affected you and ask to keep the support for the version that you need. Just try to be more mindful when doing so next time.

**Comment by tallesl** [comment]
5.5.1 should support .NET Standard 2.0 again. Thanks so much for the patch folks.
