### ISSUE TITLE
We need someone new to maintain this library

### ISSUE THREAD

**Issue by ghost** [fluentscheduler/FluentScheduler#328]
Its been over 2 years and no one's maintaining this wonderful library, we need someone new to maintain it. We cannot let it rot like that, we are a community of developers who depend on this library.

Someone should setup a vote (poll) to choose a new member to maintain the library.

**Comment by ExtraTNT** [comment]
we (the company i work for) just copied it in our project and changed it a bit... i can try to get all in my fork  (should be public), but i don't have the capacity to really maintain it... also i am only a junior dev, i don't really have that much experience (i now how to quit vim and how to make coffee, that's it xD)...

**Comment by ghost** [comment]
> and changed it a bit

What changes have you made to your copy?

**Comment by ExtraTNT** [comment]
currently i only have one, fixes a bug, where code can be executed twice...

but in the version, we have at work (was just the code from my version copy pasted in our core), i also made a change to the runEvery, so that you can use ms... (the lib is not mend to do this, there are a few problems, if you go below ~50ms (depending on your cpu) but we needed it...)
can clean it a bit up and make a v7 branch on my repo, but currently i have a few things todo for school and also for work...

**Comment by ExtraTNT** [comment]
so, i updated my fork...
have fun with it...
(can't say, that it is 100% bug free or that all unit tests run (patched it in the browser on my gaming machine xD))

**Comment by ghost** [comment]
Your fork or someone's else doesn't help, i'm not going to use a custom forked version of this library which will introduce bugs in my code. I need the original branch updated accordingly with stable releases and consistency.

I'm sorry but I'm not going to use anyone's fork, only the original. I only trust the original nuget, no other's.

**Comment by ExtraTNT** [comment]
you can copy the code, put it in your project and change it... in this case...
but would recommend, that you use the fix i made for the doubble execution bug (the ms-timing is also low risk, since it only gives you possibilities, without changing the logic)
i don't think, that the current maintainer will pick it up soon, so a fork is currently your only option... thats a problem you face with foss, you don't get enough money, so you only maintain it for "fun" -> most people don't donate to small libs, only to big projects...
