### ISSUE TITLE
CRON expressions

### ISSUE THREAD

**Issue by hoghweed** [fluentscheduler/FluentScheduler#34]
Hi,
I've chosen your implementation of a task scheduler because I like the codebase and the fact that the code is using the TPL. 

I need to extend the library to support the ability to schedule based on cron espressions. I saw that the Schedule CalculateNextRun Func is internal, so It's impossible for me to implement such a thing.

Now I have to import all your codebase in my project, modified for my needs, but this is not what I really want, so it's possible to have a version which enables extensions?

Thanks

**Comment by tallesl** [comment]
I'm putting this on "on hold" (for comments and opinions from others), even though is an old issue.

I don't know if I like the idea of the consumer hooking up how the calculation is done but supporting cron out of the box might not be a bad idea...

**Comment by Thanood** [comment]
As far as I can see [Schedule.cs](https://github.com/fluentscheduler/FluentScheduler/blob/e8aacb99f2b3ea4ae2ee50482fe5c2f4295806d2/Library/Model/Schedule.cs) (a public class) is using the builder pattern. So IMO you could support "builder-style" extension methods in that class, right?

These methods - for example ```FromCronExpression(expression)``` - could parse the expression and use the builder Methods which are already provided.

But I'm not sure if that's practical at all because I'm not that experienced with cron calculation. :smile:

**Comment by nvsoares** [comment]
Hi @tallesl.
When do you think to provide support for scheduling from cron expressions?
Is very useful and important to give the applications the flexibility that each client / work needs.

**Comment by jozefizso** [comment]
With internal `Schedule.CalculateNextRun` we cannot implement our custom `ITimeRestrictableUnit` types.

It will help to make this property public.

**Comment by MERamadan** [comment]
Any updates on this feature? It is idle for 4 years now. 
Cron expressions are a curcial feature for any scheduling engine to be able to have flexibility on job schedules and store/load the jobs schedules from a database.

**Comment by tallesl** [comment]
See #214.
