### ISSUE TITLE
Support daylight saving time

### ISSUE THREAD

**Issue by ksavelev** [fluentscheduler/FluentScheduler#62]
Hi guys,

I walked through the code and couldn't find place where it deals with daylight saving changes.

Any plans to supported this?

**Comment by tallesl** [comment]
Good pick!

That's definitely something that the library should consider.

I guess it's just a matter of getting the [DaylightTime] with [TimeZone].[CurrentTimeZone].[GetDaylightChanges] and playing with its [Start], [End] and [Delta].
Anyway, it should be done with care (not that hard to mess up the calculation IMO).

[DaylightTime]: https://msdn.microsoft.com/library/System.Globalization.DaylightTime
[TimeZone]: https://msdn.microsoft.com/library/System.TimeZone
[CurrentTimeZone]: https://msdn.microsoft.com/library/System.TimeZone.CurrentTimeZone
[GetDaylightChanges]: https://msdn.microsoft.com/library/System.TimeZone.GetDaylightChanges
[Start]: https://msdn.microsoft.com/library/System.Globalization.DaylightTime.Start
[End]: https://msdn.microsoft.com/library/System.Globalization.DaylightTime.End
[Delta]: https://msdn.microsoft.com/library/System.Globalization.DaylightTime.Delta

**Comment by tallesl** [comment]
I'm not planning to support DST anytime soon (at least not until some refactoring on [TaskManager](https://github.com/fluentscheduler/FluentScheduler/blob/87d8d4e/Library/TaskManager.cs)), but I added [a remark on README](https://github.com/fluentscheduler/FluentScheduler/blob/87d8d4e/README.md#daylight-saving-time).

Since it's on README now (and won't be forgotten) I'm closing this one.
