### ISSUE TITLE
Support .NET Core and UAP

### ISSUE THREAD

**Issue by HakanL** [fluentscheduler/FluentScheduler#67]
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
FluentScheduler 3.1.46 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'Framework'.

**Comment by jgeurts** [comment]
Hakan,
Are you familiar porting to .net core? If so, would you be interested in helping to port this library?

**Comment by tallesl** [comment]
In a couple of days I'll get my Windows 10 box back, I can take a look on it.
Since FluentScheduler doesn't rely on many dependencies (we even use client profile), [it should be possible](https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core).

@HakanL 

What's your project target/framework version? Are you using VS 2015?

@jgeurts

Hey Jim, good to see you.
I have an interest in .net core myself, I was just waiting for an excuse to play with it. Here it is :smiley:

(btw, sorry for letting some issues accumulate, I was on vacation and completely off any development work)

**Comment by HakanL** [comment]
I'm porting a project that is using FluentScheduler to .NET Core, but it is my first to port so I can't say I'm too familiar. But I can take a look at it.

I'm trying to build something to run on Windows 10 IoT, yes I'm using VS2015, I think that's a requirement for .NET Core (but I may be wrong on that).

**Comment by HakanL** [comment]
For reference: https://oren.codes/2015/07/29/targeting-net-core/

**Comment by HakanL** [comment]
Ok, I think I got it working now, I can add the FluentScheduler to my UWA project. I had to make a few changes to make it compatible with .NET Core, please review.

**Comment by tallesl** [comment]
I loaded up your pr in two different machines, one with VS 2013 and another 2015.
The VS 2013 one simply didn't load the PortableLibrary project (not supported) but the other projects were fine. On my VS 2015 everything compiled with no problems.

I'm testing your pr this weekend (and implement some of the "soon" labeled issues), won't take long until I merge and publish the NuGet package (I promise!).

I'm closing this since there's the pr to discuss further (#69).

**Comment by HakanL** [comment]
Are we close to release a new NuGet package? Thx!

**Comment by tallesl** [comment]
@HakanL Yup, I'm just finishing a last change (getting rid of the registry altogether and just use the task manager) and then it's publishing time ([it's in another branch by the way](https://github.com/fluentscheduler/FluentScheduler/tree/breaking-changes)).

If I'm not mistaken, we have to make a separate package for the portable one, a FluentScheduler.Portable (right?). Do you mind helping testing that one when it's done?

**Comment by HakanL** [comment]
Cool.

No, you shouldn't have to create a separate package for UWP, part of my PR included changes to the nuspec file to support both (and I tested that locally).

I'll be happy to test it out, even the non-published nupkg file.

**Comment by tallesl** [comment]
@HakanL 

Ah, I see now, it's just another target on the package just as for different .NET versions.

I postponed the *getting rid of the registry* thing I mentioned (#67), the implementation showed to be trickier than it seems and it's been awhile since the last package release.

I finished the [4.0.0] release. From what I've tested so far it seems to be OK.

I'm going to test a little bit further tomorrow and after you give your OK too I publish on nuget.org (in the meanwhile you can get the package for testing on the release page here on GitHub, it's attached there) and merge the [breaking-changes] branch to master.

Note that there are [some silly breaking changes] before testing it out. And of course thanks for the help!

[4.0.0]: https://github.com/fluentscheduler/FluentScheduler/releases/tag/4.0.0
[breaking-changes]: https://github.com/fluentscheduler/FluentScheduler/tree/breaking-changes
[some silly breaking changes]: https://github.com/fluentscheduler/FluentScheduler/tree/breaking-changes#upgrading-from-version-3

**Comment by HakanL** [comment]
It looks good, I can run 4.0.0 both on RPi and x86-emulator using .NET Core.
