### ISSUE TITLE
 Collection was modified when getting AllSchedules

### ISSUE THREAD

**Issue by ArtemAvramenko** [fluentscheduler/FluentScheduler#77]
I try to find job with specified name:
`var tasks = JobManager.AllSchedules.Where(item => item.Name == 'MyJob').ToList();`

but sometimes I get an exception:
```
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Additional information: Collection was modified; enumeration operation may not execute.

**Comment by tallesl** [comment]
Yup, that's a bug.

Gladly is super easy to fix, the problem is that this [little line] returns the actual reference of the collection used by the JobManager rather than a (shallow) copy.
Adding a ToList() call should fix it.

In the meanwhile you can add a ToList call yourself after AllSchedules to make the bug go away in the version you're using:

```cs
var tasks = JobManager.AllSchedules.ToList().Where(item => item.Name == 'MyJob').ToList();
```

[little line]: https://github.com/fluentscheduler/FluentScheduler/blob/d71b969fbbeed28361813240cc2d56c64fc236eb/Library/JobManager.cs#L182
