### ISSUE TITLE
GetJobInstance only called once (jobs are always singletons)

### ISSUE THREAD

**Issue by richardsorensson** [fluentscheduler/FluentScheduler#82]
When using a Dependency Injector like Autofac it could be nice if GetJobInstance in IJobFactory was called each time as it's the DI's job to resolve the job.

Right now this causes issues as GetJobInstance is only called once, so the jobs are always singletons, but needs to be refereshed with new correlation id's for each run.

**Comment by tallesl** [comment]
Unfortunately that really seems to be the case and it should be fixed (specially considering that the library claims to support dependency injection out of the box).

Fortunately it seems to be easy to fix, I get back to you a few days.

In the meanwhile, if someone need a workaround this issue, one can simply do:

```cs
Schedule(() => myJobFactoryInstance.GetJobInstance<MyJob>.Execute())
```

Instead of:

```cs
Schedule<MyJob>()
```
